export const NEGATIVE_REQUEST = "NEGATIVE_REQUEST";
export const NEGATIVE_SUCCESS = "NEGATIVE_SUCCESS";
export const NEGATIVE_ERROR = "NEGATIVE_ERROR";
export const NEGATIVE_FILTER = "NEGATIVE_FILTER";
