export const NOTIFICATIONS_REQUEST = "NOTIFICATIONS_REQUEST";
export const NOTIFICATIONS_FILTER = "NOTIFICATIONS_FILTER";
export const NOTIFICATIONS_SUCCESS = "NOTIFICATIONS_SUCCESS";
export const NOTIFICATIONS_ERROR = "NOTIFICATIONS_ERROR";
export const NOTIFICATIONS_FILTER_CHANGE = "NOTIFICATIONS_FILTER_CHANGE";
export const NOTIFICATIONS_READ = "NOTIFICATIONS_READ";

export const NOTIFICATIONS_CURRENT_REQUEST = "NOTIFICATIONS_CURRENT_REQUEST";
export const NOTIFICATIONS_CURRENT_SUCCESS = "NOTIFICATIONS_CURRENT_SUCCESS";
export const NOTIFICATIONS_CURRENT_ERROR = "NOTIFICATIONS_CURRENT_ERROR";
export const NOTIFICATIONS_CURRENT_READ = "NOTIFICATIONS_CURRENT_READ";
